<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Logbook Week {{ $log->week }}</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gray-50 font-sans text-gray-800">

    <div class="max-w-4xl mx-auto p-6 bg-white shadow-lg mt-10 rounded-lg border">

        <!-- Header -->
        <div class="flex justify-between items-center border-b pb-4 mb-6">
            <div>
                <h1 class="text-2xl font-bold">Student Industrial Work Experience Scheme</h1>
                <p class="text-gray-600">Week {{ $log->week }} Logbook</p>
            </div>

            @if($log->user->passport)
                <img src="{{ asset('storage/passports/' . $log->user->passport) }}"
                     alt="Student Passport"
                     class="w-24 h-24 rounded-lg border object-cover">
            @endif
        </div>

        <!-- Student Info -->
        <div class="grid grid-cols-2 gap-4 mb-6">
            <div>
                <p class="font-semibold">Student Name:</p>
                <p>{{ $log->user->name }}</p>
            </div>
            <div>
                <p class="font-semibold">Email:</p>
                <p>{{ $log->user->email }}</p>
            </div>
            <div>
                <p class="font-semibold">Week:</p>
                <p>{{ $log->week }}</p>
            </div>
            <div>
                <p class="font-semibold">Duration:</p>
                <p>{{ $log->start_date }} → {{ $log->end_date }}</p>
            </div>
        </div>

        <!-- Activities -->
        <div class="mb-6">
            <h2 class="text-lg font-semibold mb-2 border-b pb-1">Activities / Summary</h2>
            <p class="text-gray-700 whitespace-pre-line">{{ $log->activities }}</p>
        </div>

        <!-- Company Endorsement -->
        <div class="mb-6">
            <h2 class="text-lg font-semibold mb-2 border-b pb-1">Company Endorsement</h2>
            <div class="flex flex-col md:flex-row md:items-center gap-6">

                @if($log->company_stamp)
                    <div class="flex flex-col items-center">
                        <p class="font-medium text-gray-600 mb-1">Company Stamp</p>
                        <img src="{{ asset('storage/stamps/' . $log->company_stamp) }}"
                             alt="Company Stamp"
                             class="w-32 h-32 object-contain border rounded">
                    </div>
                @else
                    <div class="flex flex-col items-center">
                        <p class="font-medium text-gray-600 mb-1">Company Stamp</p>
                        <div class="w-32 h-32 border rounded flex items-center justify-center text-gray-400">Not Provided</div>
                    </div>
                @endif

                @if($log->company_signature)
                    <div class="flex flex-col items-center">
                        <p class="font-medium text-gray-600 mb-1">Company Signature</p>
                        <img src="{{ asset('storage/signatures/' . $log->company_signature) }}"
                             alt="Company Signature"
                             class="w-32 h-32 object-contain border rounded">
                    </div>
                @else
                    <div class="flex flex-col items-center">
                        <p class="font-medium text-gray-600 mb-1">Company Signature</p>
                        <div class="w-32 h-32 border rounded flex items-center justify-center text-gray-400">Not Provided</div>
                    </div>
                @endif

            </div>
        </div>

        <!-- Footer -->
        <div class="border-t pt-4 mt-6 text-sm text-gray-500 flex justify-between items-center">
            <span>Generated by WEMS</span>
            <span>{{ date('F j, Y') }}</span>
        </div>

    </div>

</body>
</html>
